from starwars_api_classes import *

print('<--------------------------- 1. Printing data retrieved from swapi --------------------------->')
starwars = Starwars()
starships = starwars.get_starwars_data()
pprint(starships)
print()
print('---------------------------------------------------------------------------------------------------')
print()
print('<-------------------------- 2. Printing data with pilot values replaced with names -------------------------->')
refined_starships = starwars.get_pilot_info(starships)
pprint(refined_starships)
print()
print('---------------------------------------------------------------------------------------------------')
print()
print('<-------------------------- 3. Printing data with pilot values replaced with ID\'s -------------------------->')
starships_id = starwars.replace_with_id(refined_starships)
pprint(starships_id)
print()
print('---------------------------------------------------------------------------------------------------')
print()
print('<-------------------------- 4. Inserting data into specified collection on MongoDB -------------------------->')
starwars.insert_data(starships_id, overwrite=True)
